#!/bin/bash


#This script uses the smhicleaner.sh script and produces clean datasets as csv files in code/ClnData folder for the city inputed

#take dataset folder path and the city of interest as input
DATAPATH=$1 # no spaces!
CITY=$2

#recording original directory where script is run
OriginalDir=`pwd` 

#move to the dataset folder to retrieve the file for the city if it's there
cd $DATAPATH
CITYFILE="$DATAPATH/`grep -i -l -m 2 $CITY *`" # - m 2

#check if file for city was found, notify user if not
if [[ "x$CITYFILE" == "x$DATAPATH/" ]]; then
	echo "City $CITY not found, exiting"
	exit 1
fi

#//make a temporary directory that is deleted end of script
mkdir $OriginalDir/SmhiCleaner/CleanerOutputs
#//change current directory to CleanerOutputs where files will be produced by smhicleaner.sh
cd $OriginalDir/SmhiCleaner/CleanerOutputs

#run the smhicleaner.sh script to produce clean csv datasets
$OriginalDir/SmhiCleaner/smhicleaner.sh $CITYFILE > ./shmicleaner.log 2>&1

#retrieve the final clean csv dataset file in the CleanerOutputs folder
RAWFILENAME=$(basename $CITYFILE)

RAWFILENAME="rawdata_${RAWFILENAME}"

#copy the clean dataset file to code/ClnData for easy access by the project code 
cp $RAWFILENAME $OriginalDir/code/ClnData/Clean$CITY.csv

rm * #remove the files generated by smhicleaner in the temporary folder CleanerOutputs 

cd $OriginalDir #Switch back to starting directory

rmdir $OriginalDir/SmhiCleaner/CleanerOutputs #//delete the empty temporary folder
